AbitVstup/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from abiturients import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('abiturients.urls'))
]

abiturients/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('',RegionView.as_view(),name="regions"),
    path('region/<int:pk>/vnzs/', VnzListView,name="vnzs"),
    path('vnz/<int:pk>/specialties',SpecListView, name="specialties"),
    path('specialty/<int:pk>/',SpecView, name="abits"),
    path('statistic/',get_statistic_for_region,name="stat"),
    path('spec/',get5Specilaties,name="top5spec"),
    path('students/',statistic_for_polygon,name="statistic"),
    path('doc/',doc,name="doc"),
    path('help/',help,name='help')


    # path('v/',vns),
    # path('delete/',Delete),
    # path('add/',addvnzs),
    # path('spec/',addspec,)

]

abiturients/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Region(models.Model):
    Region_name = models.CharField(max_length=100)

    def __str__(self):
        return "{0} {1}".format(self.id,self.Region_name)




class VNZ(models.Model):
    name = models.CharField(max_length=500)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return "{0}".format(self.name)


class Specialty(models.Model):
    name_of_specialty = models.CharField(max_length=250)


    steps = (
        ('B','Бакалавр'),
        ('M','Магістр'),

    )
    step = models.CharField(max_length=10,choices=steps, default='B')

    count_of_abiturients = models.PositiveIntegerField()
    count_of_contract_abiturients = models.PositiveIntegerField(default=0)
    vnz = models.ManyToManyField(VNZ)
    forms = (
        ('day', 'денна'),
        ('part-time', 'заочна'),
        ('afternoon', 'вечірня')
    )

    form  = models.CharField(max_length=20,choices=forms)
    students = models.ManyToManyField('Abiturient_Statement')
    def __str__(self):
        return '{0}'.format(self.name_of_specialty)


class Subject(models.Model):
    name_of_subject = models.CharField(max_length=250)
    coef = models.FloatField(default=0.1)
    mark = models.IntegerField(default=100,null=True)
    specialty = models.ManyToManyField(Specialty)

    def __str__(self):
        return "{0}".format(self.name_of_subject)


class Abiturient_Statement(models.Model):
    username = models.CharField(max_length=80)
    priority = models.CharField(max_length=10)
    mark = models.FloatField()
    status = models.CharField(max_length=100,null=True)
    isdocument = models.CharField(max_length=1, default='+')
    vnzs = models.ManyToManyField(VNZ)


    def __str__(self):
        return "{0}".format(self.username)

abiturients/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.http import HttpResponse,JsonResponse
import csv
from .models import *
from django.views import generic
from django.db.models import Q,aggregates
from django.core import serializers
from collections import Counter
import math
import  multiprocessing
# Create your views here.


class RegionView(generic.ListView):
    model = Region
    template_name = "abiturients/index.html"

def VnzListView(request,pk):
    region = Region.objects.get(pk=pk)

    allvnzs = region.vnz_set.all().order_by('name')

    paginator = Paginator(allvnzs,25)

    page = request.GET.get('page')
    vnzs = paginator.get_page(page)
    return render(request,"abiturients/vnzs.html",{'vnzs': vnzs,'region':region})


def SpecListView(request,pk):
    vnz = VNZ.objects.get(pk=pk)

    specialties_set = vnz.specialty_set.order_by('name_of_specialty')

    paginator = Paginator(specialties_set,100)
    page = request.GET.get('page')
    specialties = paginator.get_page(page)

    return render(request,"abiturients/specialties.html",{'specialties':specialties,'vnz':vnz})


def SpecView(request,pk):
    specialty=Specialty.objects.get(pk=pk)
    studs = specialty.students.order_by(('-mark'))


    paginator = Paginator(studs,100)
    page = request.GET.get('page')
    students = paginator.get_page(page)

    return render(request,"abiturients/students.html",{'students':students,'specialty':specialty})




def get_statistic_for_region(request):
    pk = request.GET.get('pk')
    region = Region.objects.get(pk=pk)

    vnzs_count = region.vnz_set.count()
    univercities = region.vnz_set.filter(name__contains="університет").exclude(name__contains="коледж")\
        .exclude(name__contains="філія").exclude(name__contains="інститут")\
        .exclude(name__contains="пункт").exclude(name__contains="університету")

    academies = region.vnz_set.filter(name__contains="академія").exclude(name__contains="інститут")
    institutes = region.vnz_set.filter(name__contains="інститут").exclude(name__contains="коледж")\
        .exclude(name__contains="товариство")
    colleges = region.vnz_set.filter(Q(name__contains="коледж")|Q(name__contains="Коледж")).exclude(name__contains="філія")
    count = univercities.count()
    acount = academies.count()
    icount = institutes.count()
    colcount = colleges.count()
    elsecount=vnzs_count-(count+acount+icount+colcount)


    return JsonResponse({'ucount':count,'acount':acount,'icount':icount,'colcount':colcount,'elsecount':elsecount})




def get5Specilaties(request):
    pk=request.GET.get('pk')
    vnz=VNZ.objects.get(pk=pk)

    specilaties = list(vnz.specialty_set.annotate(counts=aggregates.Count('students')).order_by('-counts')[:5])
    specilaties.sort(key=lambda x: x.count_of_abiturients)
    specilaties = serializers.serialize('json',specilaties)
    data={
        "specs":specilaties
    }
    return JsonResponse(data)

def get10students(request):
    pk = request.GET.get('pk')

    spec=Specialty.objects.get(pk=pk)

    students = list(spec.students.order_by('-mark')[:10])
    students.sort(key=lambda x: x.username)
    # students = students.order_by('username')
    students = serializers.serialize('json',students)
    statistic_for_polygon(spec)
    data={
        'students': students
    }

    return JsonResponse(data)

def statistic_for_polygon(request):
    pk = request.GET.get('pk')

    spec = Specialty.objects.get(pk=pk)

    students = spec.students.order_by('mark')

    marks = [i.mark for i in students]


    n=len(marks)

    r = int(math.log(n,2))+1

    rozm = marks[-1]-marks[0]

    d=rozm/r
    s=marks[0]
    intervals=[]
    for i in range(r):
        intervals.append((s,s+d))
        s+=d

    middles=[]
    counts=[]
    for i in intervals:
        k=0
        for j in marks:
            if j>=i[0] and j<i[1]:
                k+=1
        middles.append(round((i[0]+i[1])/2,2))
        counts.append(k)

    data={
        'middles':middles,
        'counts':counts
    }

    return JsonResponse(data)



def doc(request):
    return render(request,'abiturients/doc.html')

def help(request):
    return render(request,'abiturients/file.html')











def Delete(request):


    for sp in Region.objects.all():
        for st in sp.vnz_set.all():
            st.delete()



    return HttpResponse('deleted')













def vns(request):
    vnzs = VNZ.objects.all()
    v=[]
    for i in vnzs:
        if i.specialty_set.count() != 0:
            v.append(i)

    return HttpResponse(len(v))

def readvnzs():

    with open("Vnz.csv",'r') as file:
        reader = csv.DictReader(file)

        for row in reader:
            region = Region.objects.get(Region_name=row['region'])

            vnz=VNZ.objects.create(name=row['vnz'],region=region)
            vnz.region = region


def addvnzs(request):

    readvnzs()

    return HttpResponse("succes")

def addspec(request):
    with open('st.csv','r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            vnz=VNZ.objects.filter(name=row['vnz'])
            count = 0
            kcount =0
            if row['count']!='n/a':
                count=int(row['count'])
            try:
                kcount=int(row['kcount'])
            except Exception:
                kcount=0

            spec,result=Specialty.objects.get_or_create(step=row['step'][0],name_of_specialty=row['title'],count_of_abiturients=count,
                                          count_of_contract_abiturients=kcount)
            subject=row['sub'].split(',')

            try:
                try:
                    coef=float(subject[1])
                    mark = int(subject[2])
                except ValueError:
                    coef=1
                    mark=100


                sub,res = Subject.objects.get_or_create(name_of_subject=subject[0],coef=coef,mark=mark)
            except IndexError:

                sub, res = Subject.objects.get_or_create(name_of_subject=subject[0], coef=float(subject[1]),

                                                         mark=100)

            if sub not in spec.subject_set.all():
                spec.subject_set.add(sub)

            if spec not in vnz[0].specialty_set.all():
                vnz[0].specialty_set.add(spec)
            students_name = row['students_name']
            priority = row['priority']
            mark=float(row['mark'])
            isdocument = row['isdocument']
            student,stres = Abiturient_Statement.objects.get_or_create(username=students_name,priority=priority,mark=mark,isdocument=isdocument)

            if student not in spec.students.all():
                spec.students.add(student)
            if student not in vnz[0].abiturient_statement_set.all():
                vnz[0].abiturient_statement_set.add(student)
    return HttpResponse("dndn")

abiturients/templates/abiturients/doc.html
{% extends 'abiturients/index.html' %}
{% block content %}

    <div class="doc">
        <div class="container">
            <h1 class="AbitHeader">Документація</h1>

            <div class="description">
                <p class="about">
                    Даний проект було збудовано з метою надати абітурієнтам інформацію про їхнє перебування в рейтингу абітурієнтів а також показати інформацію про ці заклади та спеціальності в них.
                </p>
                <p class="about">
                    Для побудови даного проекту було використано багато різних технологій. Зокрема для розробки лицьової частини сайту (фронтенду) було використано мову розмітки HTML,
                    таблицю стилів CSS, мову програмування JavaScript з її бібліотеками Jquery (<a href="https://jquery.com/">https://jquery.com/</a> )та Chart.js
                    (<a href="https://www.chartjs.org/">https://www.chartjs.org/</a>), також CSS фреймворк Bootstrap 4.0 який розроблений компанією Twitter для полегшення роботи з адаптивністю сайту. Детальнішу інформацію про фреймворк можна отримати за посиланням
                    <a href="https://getbootstrap.com/">https://getbootstrap.com/</a>.
                </p>
                <p class="about">
                    Для реалізації серверної частини сайту(бекенд) було використано мову програмування пайтон, оскільки  вона непогано себе показує в веб розробці і її веб-фреймворк Django 2.2.1.
                    <a href="https://www.djangoproject.com/">https://www.djangoproject.com/</a>Щоб отримати детальнішу інфорацію перейдіть за посиланням
                    <a href="https://www.python.org/
                    ">https://www.python.org/
                    </a>.
                    З реляційних баз даних було використано PostgresSql 10.0
                    <a href="https://www.postgresql.org/">https://www.postgresql.org/</a>.
                </p>
                <p class="about">
                    Для зберігання даних в базі даних було побудовано 5 основних таблиць: <b>abiturients_region,</b> <b>abiturients_specialty,</b><b>abiturients_vnz,</b><b>abiturients_subject,</b> <b>abiturients_abiturient_statement</b>.
                    До дотаткових таблиць належать таблиці створені зв’язками основних таблиць, а також таблиці створені фреймворком Django по замовчуванню <b>auth_user,</b> <b>auth_group,</b> <b>permissions,</b> <b>sessions</b> для підтримки аунтефікації,авторизації та сесій. Основні налаштування бази даних знаходяться на малюнку.
                    {% load static %}
                    <img class="centrimg" src="{% static 'css/images/viber image 2019-05-20 , 22.33.13.jpg' %}" alt="">
                </p>
                <p class="about">
                    За допомогою django ORM ми можемо представити таблиці у вигляді класів.
                    Розглянемо кожну із 5-ти основних таблиць.
                </p>
                <p class="about">
                    <strong>Region</strong>
                    <p class="d-flex">
                    <img src="{% static 'css/images/viber image 2019-05-20 , 22.36.26.jpg' %}" alt="" style="width: 40%">
                    <img src="{% static 'css/images/viber image 2019-05-20 , 22.44.35.jpg' %}" alt="" style="width: 60%">

                    </p>
                </p>
                <p class="about">
                    <stro>VNZ</stro>
                    <p class="d-flex">
                    <img src="{% static 'css/images/viber image 2019-05-20 , 22.36.57.jpg' %}" alt="" style="width: 40%">
                    <img src="{% static 'css/images/viber image 2019-05-20 , 22.46.01.jpg' %}" alt="" style="width: 60%">

                    </p>
                </p>

                <p class="about">
                    <stro>Abiturient Statement</stro>
                    <p class="d-flex">
                    <img src="{% static 'css/images/viber image 2019-05-20 , 22.40.13.jpg' %}" alt="" style="width: 40%">
                    <img src="{% static 'css/images/viber image 2019-05-20 , 22.41.32.jpg' %}" alt="" style="width: 60%">

                    </p>
                </p>
                <p class="about">
                    Фреймворк Django працює за принципом MVT аналог MVC тільки замість терміна Controller в Django прийнято вживати термін Template. Так база даних з таблицями вже готова, потрібно  ці дані якось представити. Для цього було побудовано спеціальні функції(Views).
                </p>
                
                <p class="about">
                    Дані було використано з сайтів <a href="http://www.vstup.info/">http://www.vstup.info/</a>,<a
                        href="https://abit-poisk.org.ua/">https://abit-poisk.org.ua/</a>.
                </p>
                <p class="about">
                    Так як API у них відсутнє потрібно якось спарсити цю інформацію. Для цього була знову використана мова python з її бібліотекою BeautifulSoup 4.0.
                    <a href="https://www.crummy.com/software/BeautifulSoup/bs4/doc/">https://www.crummy.com/software/BeautifulSoup/bs4/doc/</a>
                </p>

                <p class="about">
                    Для візуалізації даних було використано бібліотеку Chart.js. В ній є багато готових шаблонів для діаграм і графіків.
                </p>
                <p class="about">
                    <img src="{% static 'css/images/diagram.jpg' %}" alt="" style="width: 50%" class="centrimg">
                    Для побудови діаграми ми вибираємо 5 спеціальностей з найбільшою к-стю студентів та сортуємо їх по іменах потім візуалізуємо ці дані з типом Bar.
                </p>
                <p class="about">
                    <img src="{% static 'css/images/polygon.jpg' %}" alt="" style="width: 50%" class="centrimg">
                    Для побудови графіка полігону частот ми вираємо всіх абітурієнтів з заданої спеціальності, сортуємо їх по середньому балу. Розбиваємо бали на проміжки і підраховуємо кількість студениів які входять в ці проміжки. Потім рахуємо середнє арифметичне кожного проміжку і передаємо дані через JSON формат і будуємо по цих даних графік з типом “line”.
                </p>
            </div>
        </div>
    </div>

{% endblock %}

abiturients/templates/abiturients/file.html
{% extends 'abiturients/index.html' %}
{% block content %}
<style>



    img{


        margin-top: 3rem;

        width:100%;
    }

</style>
<div class="help">
<div class="container">
    <h1>Починаємо</h1>
    <p class="about">Даний проект було збудовано з метою надати абітурієнтам інформацію про їхнє перебування в рейтингу абітурієнтів,
        а також показати інформацію про ці заклади та спеціальності в них.</p>
    <h1>AbitVstup в дії</h1>
    <li class="helpli">
        <span class="help-desc">Відкривши наш проект ми потрапляємо на головну сторінку сайту AbitVstup</span>
        {% load static %}
        <p class="about"><img src="{% static 'css/static resources/зображення_viber_2019-05-20_19-58-53.jpg' %}"></p>
    </li>
    <li class="helpli">
        <span class="help-desc">Щоб переключити слайдер необхідно натиснути на цифри,які розміщені на картинці,так як це зроблено в наступному скріншоті</span>
        <p><img src="{% static 'css/static resources/зображення_viber_2019-05-20_19-58-59.jpg' %}"></p>
    </li>
    <li class="helpli">
        <span class="help-desc">Погортавши скролом вниз ми побачимо області в яких містяться ВНЗи</span>
        <p class="about"><img src="{% static 'css/static resources/зображення_viber_2019-05-20_19-59-50.jpg' %}"></p>
    </li>
    <li class="helpli">
        <span class="help-desc">З переліку ми можемо натиснути на необхідну нам область і отримати інформацію про її заклади</span>
        <p class="about"><img src="{% static 'css/static resources/зображення_viber_2019-05-20_20-00-42.jpg' %}"></p>
    </li>
    <li class="helpli">
        <span class="help-desc">Кожен ВНЗ містить діаграму з top 5 спеціальностей</span>
        <p class="about"><img src="{% static 'css/static resources/зображення_viber_2019-05-20_21-50-07.jpg' %}"></p>
    </li>
    <li class="helpli">
        <span class="help-desc">Нижче вищезгаданої діаграми ми можемо натрапити на перелік спеціальностей</span>
        <p class="about"><img src="{% static 'css/static resources/зображення_viber_2019-05-20_21-59-05.jpg' %}"></p>
    </li>
    <li class="helpli">
        <span class="help-desc">Сайт надає нам можливість, натиснувши на одну із спеціальностей,
            переглянути абітурієнтів із їхніми середніми балами, а також діаграму яка побудована на основі їхніх даних</span>
        <p class="about"><img src="{% static 'css/static resources/зображення_viber_2019-05-20_21-59-27.jpg' %}">
            <img src="{% static 'css/static resources/зображення_viber_2019-05-20_22-23-30.jpg' %}">
        </p>
    </li>


</div>
</div>

{% endblock %}

abiturients/templates/abiturients/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}AbitVstup-Main{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
</head>
<body>
	<div class="wrapper">
		<header>
			<div class="container top-line">
				<div class="row">
					<div class="logo">

							<h1>
								<i class="fas fa-graduation-cap"></i>
								<span id="abit">Abit</span><span id="vstup">Vstup</span>

							</h1>
							<span id="downInfoForlogo">Information Page</span>

					</div>
					<div class="contacts">
							<div class="row">
							<h1 class="phone-number">
							<i class="fas fa-phone"></i>
							<span id="PhoneNumber">+38068-82-98-194</span>
							</h1>
							<h1 class="phone-number mail">
								<i class="fas fa-envelope"></i>
								<span id="mail"><a href="#">dmitrenkovolodimir@gmail.com</a></span>
							</h1>
							</div>

					</div>
				</div>

			</div>


		</header>
		<div class="navigation bg-light">
				<div class="container">
				<nav class="navbar navbar-light  navbar-expand-lg pl-0 pt-3 pb-3">
					<ul class="navbar-nav pl-0">
						<li class="nav-item">
							<a href="{% url 'regions' %}" class="nav-link">Home</a>
						</li>
						<li class="nav-item">
							<a href="#" class="nav-link">About</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'help' %}" class="nav-link">Help</a>
						</li>
						<li class="nav-item">
							<a href="{% url 'doc' %}" class="nav-link">Documentation</a>
						</li>
					</ul>
				</nav>
				</div>
			</div>
		<main>
            {% block content %}
			<div class="slider">

				<div class="slide-item" id="slide-first">
					<div class="container">
					<p class="slide-motto">
						More Then Just <strong>Studying</strong>
					</p>
					</div>
				</div>
				<div class="slide-item" id="slide-second">
					<div class="container">
					<p class="slide-motto">
						Create Your <strong>Future</strong>
					</p>
					</div>
				</div>
				<div class="slide-item" id="slide-third">
					<div class="container">
					<p class="slide-motto">
						Believe In <strong>Yourself</strong>
					</p>
					</div>
				</div>
				<div class="slider-controllers">

					<ul class="controllers">
						<li class="controller active">1</li>
						<li class="controller">2</li>
						<li class="controller">3</li>
					</ul>

				</div>
			</div>
                <div class="regions">
                    <div class="container">
                        <h1 class="AbitHeader">Regions</h1>
                        <ul class="region-list">
                            {% for region in region_list %}
                                <li class="AbitLink"><a href="{% url 'vnzs' pk=region.pk %}">{{ region.Region_name }}</a></li>
                                
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            {% endblock %}
		</main>
		<footer>
			<div class="container">
				<p>© 2019 All Rights Reserved</p>
			</div>
		</footer>
	</div>









	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="{% static 'script/slider.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
</body>
</html>

abiturients/templates/abiturients/specialties.html
{% extends 'abiturients/index.html' %}


{% block content %}

    <div class="specialties">
        <div class="container" >
            <h1 class="AbitHeader">{{ vnz.name }}</h1>
            <div class="chart">
                <canvas id="barchart"></canvas>
            </div>
            <ul class="region-list specialties-list">
                {% for spec in specialties %}
                    <li class="AbitLink"><a href="{% url 'abits' pk=spec.pk %}">{{ spec.name_of_specialty }} {{ spec.step }} {{ spec.count_of_abiturients }}</a></li>
                {% endfor %}
            </ul>

        <div class="pagination-list">

                {% if specialties.has_other_pages %}
                    <ul class="pagination">
                        {% if specialties.has_previous %}
                            <li class="arrow"><a href="?page={{ specialties.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in specialties.paginator.page_range %}
                            {% if specialties.number == i %}
                                 <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>

                            {% else %}
                                <li class="nonactive"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if specialties.has_next %}
                            <li class="arrow"><a href="?page={{ specialties.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>


        </div>


    </div>
     <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function () {
            $.ajax({
                url:{% url 'top5spec' %},
                type:"GET",
                data:{
                    'pk':{{ vnz.pk }}
                },
                dataType:'json',
                success: function (data) {
                    specs = JSON.parse(data['specs']);
                    //console.log(specs)
                    names=[];
                    counts= [];

                    for(var i=0;i<specs.length;i++){
                        names.push(specs[i]['fields']['name_of_specialty']);
                        counts.push(specs[i]['fields']['students'].length);
                    }
                    var ctx = document.getElementById('barchart');
                    var barchart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: names,
                            datasets: [{
                                label: 'top',
                                data: counts,
                                backgroundColor: [
                                    'rgba(1,159,87,0.67)',
                                    'rgba(1,159,87,0.67)',
                                    'rgba(1,159,87,0.67)',
                                    'rgba(1,159,87,0.67)',
                                    'rgba(1,159,87,0.67)',


                                ],
                                borderColor: [

                                ],
                                borderWidth: 1,
                                //lineTension: 0,

                            }]

                        },
                        options:{
                            scales:{
                                yAxes:[{
                                    ticks:{
                                        beginAtZero: true
                                    }
                                }],
                                xAxes:[{
                                    //categoryPercentage: 1.0,
                                    barPercentage: 0.7,
                                    gridLines: {
                                    offsetGridLines: true
                                }
                                }]

                            }
                        }
                    });


                }

            });



        })
    </script>
{% endblock %}

abiturients/templates/abiturients/students.html
{% extends "abiturients/index.html" %}
{% block content %}
<div class="students">
        <div class="container">
            <h1 class="AbitHeader">{{ specialty.name_of_specialty }}</h1>
            <div class="chart">
                <canvas id="linechart"></canvas>
            </div>
            <ul class="region-list specialties-list">
                {% for st in students %}
                    <li class="AbitLink"><a href="#">{{ st.username}}  середній бал: {{ st.mark }}</a></li>
                {% endfor %}
            </ul>
        <div class="pagination-list">

                {% if students.has_other_pages %}
                    <ul class="pagination">
                        {% if students.has_previous %}
                            <li class="arrow"><a href="?page={{ students.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in students.paginator.page_range %}
                            {% if students.number == i %}
                                 <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>

                            {% else %}
                                <li class="nonactive"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if students.has_next %}
                            <li class="arrow"><a href="?page={{ students.next_page_number }}">&raquo;</a></li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(function () {
                $.ajax({
                url:{% url 'statistic' %},
                type:"GET",
                data:{
                    'pk':{{ specialty.pk }}
                },
                dataType:'json',
                success: function (data) {
                    console.log(data);
                    marks = data['middles'];


                    counts= data['counts'];

                    console.log(counts);



                    var ctx = document.getElementById('linechart');
                    var linechart = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: marks,
                            datasets: [{
                                label: 'statistic',
                                data: counts,
                                backgroundColor: [
                                    'transparent',



                                ],
                                borderColor: [
                                    'rgba(1,159,87,0.67)',
                                ],
                                borderWidth: 1,
                                lineTension: 0,

                            }]

                        },
                        options:{
                            scales:{
                                yAxes:[{
                                    ticks:{
                                        beginAtZero: true
                                    }
                                }],
                                xAxes:[{
                                    //categoryPercentage: 1.0,
                                    barPercentage: 0.8,
                                    gridLines: {
                                    offsetGridLines: true
                                }
                                }]

                            }
                        }
                    });



                }

            });




        })
    </script>
{% endblock %}